#Honor Pledge: I pledge that I have neither given, nor received any help on this assignment.
#Ehtsham Nisar

All: Driver.class Stack.class Address.class Student.class

Driver.class: Driver.java
	javac Driver.java
Stack.class: Stack.java
	javac Driver.java
Address.class: Address.java
	javac Address.java
Student.class: Student.java
	javac Student.java
clean:
	rm *.class