#Honor Pledge: I pledge that I have neither given, nor received any help on this assignment.
#Ehtsham Nisar
#All.exe:All.class

All.class: Driver.class Employee.class StaffPharmacist.class StaffTechnician.class PharmacyManager.class SeniorTechnician.class
	

Driver.class: Driver.java
	javac Driver.java
Employee.class: Employee.java
	javac Employee.java
StaffPharmacist.class: StaffPharmacist.java
	javac StaffPharmacist.java
StaffTechnician.class: StaffTechnician.java
	javac StaffTechnician.java
PharmacyManager.class: PharmacyManager.java
	javac PharmacyManager.java
SeniorTechnician.class: SeniorTechnician.java
	javac SeniorTechnician.java
clean:
	rm*.class